=== faithmcqueen/xml-assign2/xml/supporttickets.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- starting to define our tickets -->
	<xs:element name="tickets">
		<xs:complexType>
			<!-- element tickets (ticket) -->
			<xs:sequence>
				<xs:element name="ticket" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
				<!-- Date -->
				<xs:element name="date" type="xs:date" />
				<!-- Status -->
				<xs:element name="status" type="status" />
				<!-- userID -->
				<xs:element name="userid" type="xs:string" />
				<!-- Category -->
				<xs:element name="category" type="categories" />
				<!-- Subject -->
				<xs:element name="subject" type="xs:string" />
				<!--Messages -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="message">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="username" type="usernames" />
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
				<!-- Image/Screenshot upload -->
				<xs:element name="image" minOccurs="0" maxOccurs="unbounded">
	                <xs:complexType>
	                  <xs:simpleContent>
	                    <xs:extension base="xs:string">
	                      <xs:attribute name="image" type="imgfiles" />
	                      <xs:attribute name="description" type="xs:string" />
	                    </xs:extension>
	                  </xs:simpleContent>
	                </xs:complexType>
            	</xs:element>
				<!-- closing the sequence, and element -->
				</xs:sequence>
			</xs:complexType>
		</xs:sequence>
	</xs:complexType>
</xs:element>
	<!-- declaring our status types to fill in our status element -->
	<xs:simpleType name="status">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ongoing" />
			<xs:enumeration value="resolved" />
			<xs:enumeration value="unresolved" />
		</xs:restriction>
	</xs:simpleType>
	<!-- declaring our category types to fill in our category element -->
	<xs:simpleType name="categories">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Purchasing Orders" />
			<xs:enumeration value="Product Returns" />
			<xs:enumeration value="Product Inquiry" />
			<xs:enumeration value="Wholesale Inquiry" />
		</xs:restriction>
	</xs:simpleType>
	<!-- Declaring our image file attributes - reference from class example books.xsd -->
	<xs:simpleType name="imgfiles">
	    <xs:restriction base="xs:string">
	    	<xs:pattern value="[-_0-9A-Za-z]{3,}\.(jpg|png|gif|jpeg)" />
	    </xs:restriction>
    </xs:simpleType>
<!-- end of schema -->
</xs:schema>

=== faithmcqueen/xml-assign2/xml/supporttickets.xml
<?xml version="1.0" encoding="utf-8" ?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="supporttickets.xsd">
	<ticket>
		<id>0001</id>
		<date>January 15, 2020</date>
		<status>Ongoing</status>
		<userid>003</userid>
		<category>Purchasing Orders</category>
		<subject>Cannot fill out purchase order</subject>
		<message usertype="client">Hello! When I try and fill out my purchase order and hit submit in order to place the order, the form disappears and nothing happens.</message>
		<message usertype="admin">Hi there! Can you send along a screenshot of what you see when you submit the form so I can see in more detail what you are seeing?</message>
		<image image="screenshot.jpg"></image>
	</ticket>
	<ticket>
		<id>0002</id>
		<date>February 1, 2020</date>
		<status>Resolved</status>
		<userid>004</userid>
		<category>Product Returns</category>
		<subject>Defective items in shipment</subject>
		<message usertype="client">When my order arrived I saw that I had defective products in my shipment. I've attached an image here. Will I be able to get these replaced?</message>
		<image image="defectiveproducts.jpg"></image>
		<message usertype="admin">Of course. We will begin processing the defectiveitems as a return and refunding your account the cost of those items.</message>
		<message usertype="client">Thank you! I will ship the defective items back.</message>
		<message usertype="admin">Great. The return has been processed, when we receive the defective items the refund will be released to your account. Is there anything else I can help you with?</message>
		<message usertype="client">That's everything, thank you!</message>
	</ticket>
</tickets>
